### ISSUE TITLE
Crops get stuck at 12% and cease to grow.

### ISSUE THREAD

**Issue by Lethann** [InfinityRaider/AgriCraft#880]
AgriCraft 2.0.0-0.7.0-a12
Custom Modpack on a private server

I wish I had more bug info for this but after the last 3-4 days of non-stop growing and cross breeding I've run into this issue several times. At seemingly random times a crop will pop to the first 12% stage and then never grow beyond it despite EU2 watering can usage and _several_ ingame days passing and **IRL** HOURS going by.

Maybe it's just bad luck, I don't know, but it's happened a-lot- to me over the last 3-4 days and seems a bit more than bad luck. I haven't touched the customization files so not sure if there is something in there that might take care of this.

**Comment by RlonRyan** [comment]
Fixed. The plants were ignoring the base growth chance and were using only the bonus growth chance which is low.

**Comment by Waterspark63** [comment]
I'm now having this issue on the latest 1.20.1 version (4.0.2-Beta). I crossbred a poppy from a sugarcane plant and a melon plant. Checking in on it occasionally, it's been two irl days, and the poppy seeds are still at 12.5% grown, but the growth state also is preserved on breaking and placement of the seeds. (I can move the poppy seeds, and it still shows 12.5% grown, with or without crop sticks.) It's my own custom modpack, here's the [modlist](https://gist.github.com/Waterspark63/67c58a2d7186540083ef898d9cab36dc)

**Comment by Ketheroth** [comment]
what's the soil under your poppy crop ?

**Comment by Waterspark63** [comment]
.. I realize what it is now, I apologize.
